package:
  name: dynakit
  version: 0.0.3
source:
  sha256: a546be9801a2224fcb56e54ad06c184ebb2035f278c4c30e3a21278462ddda65
  url: https://files.pythonhosted.org/packages/b2/30/f552ac37672ade70d597cb0dc1960073ed49c6fe2db41cf8d8165f5cc3b6/dynakit-0.0.3.tar.gz
about:
  dev_url: https://dynapy.github.io
  doc_url: https://dynapy.github.io
  home: https://dynapy.github.io
  license: Apache Software
  license_family: APACHE
  summary: Machine Learning Toolkit for LS-Dyna Simulations
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dynapy
requirements:
  host:
  - pip
  - python
  - packaging
  - lasso-python>=1.5.0
  - diversipy==0.8
  - numpy==1.20.1
  - pandas==1.1.5
  - pyDOE==0.3.8
  - PyYAML==5.4.1
  - qd==0.8.9
  - scipy==1.6.0
  run:
  - pip
  - python
  - packaging
  - lasso-python>=1.5.0
  - diversipy==0.8
  - numpy==1.20.1
  - pandas==1.1.5
  - pyDOE==0.3.8
  - PyYAML==5.4.1
  - qd==0.8.9
  - scipy==1.6.0
test:
  imports:
  - dynakit
