# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"FE": "10_FE.ipynb",
         "ML": "20_ML.ipynb"}

modules = ["FE.py"]

doc_url = "https://dynapy.github.io/dynakit/"

git_url = "https://github.com/dynapy/dynakit/tree/main/"

def custom_doc_links(name): return None
